services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    expose:
      - "2053"
      - "443"
    volumes:
      - ./3x-ui/data:/etc/x-ui
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/etc-letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - webnet
    depends_on:
      - 3x-ui

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
    networks:
      - webnet

networks:
  webnet:
    driver: bridge