services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - "2053:2053"
    volumes:
      - ./3x-ui/data:/etc/x-ui
    environment:
      - XRAY_DOMAIN=${XRAY_DOMAIN}
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - 3x-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
    environment:
      - PANEL_DOMAIN=${PANEL_DOMAIN}
      - XRAY_DOMAIN=${XRAY_DOMAIN}
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - webnet

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
    networks:
      - webnet

  https-proxy:
    build: ./https-proxy
    container_name: https-proxy
    restart: unless-stopped
    volumes:
      - ./https-proxy/config:/etc/tinyproxy/config
      - ./https-proxy/users:/etc/tinyproxy/users
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
    ports:
      - "8443:8080"
    networks:
      - webnet

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/jail.d:/etc/fail2ban/jail.d
      - ./fail2ban/filter.d:/etc/fail2ban/filter.d
      - ./fail2ban/action.d:/etc/fail2ban/action.d
      - /var/log:/var/log:ro
    environment:
      - TZ=Europe/Moscow

networks:
  webnet:
    driver: bridge